# Generated by Django 5.2.7 on 2025-11-15 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idalumno', models.IntegerField(db_column='idalumno', primary_key=True, serialize=False)),
                ('codigougel', models.IntegerField(blank=True, db_column='codigougel', null=True)),
                ('nombres', models.CharField(db_column='nombres', max_length=100)),
                ('apellidos', models.CharField(db_column='apellidos', max_length=100)),
                ('edad', models.IntegerField(blank=True, db_column='edad', null=True)),
                ('dni', models.CharField(db_column='dni', max_length=15, unique=True)),
                ('idgrado_trabajado', models.IntegerField(blank=True, db_column='idgrado_trabajado', null=True)),
                ('idpadre', models.IntegerField(blank=True, db_column='idpadre', null=True)),
            ],
            options={
                'db_table': 'alumno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('idasignatura', models.IntegerField(db_column='idasignatura', primary_key=True, serialize=False)),
                ('area', models.CharField(db_column='area', max_length=50)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('cant_horas', models.IntegerField(blank=True, db_column='cant_horas', null=True)),
            ],
            options={
                'db_table': 'asignatura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AsignaturaTrabajada',
            fields=[
                ('idasignatura_trabajada', models.IntegerField(db_column='idasignatura_trabajada', primary_key=True, serialize=False)),
                ('idgrado_trabajado', models.IntegerField(blank=True, db_column='idgrado_trabajado', null=True)),
                ('idprofesor', models.IntegerField(blank=True, db_column='idprofesor', null=True)),
                ('idasignatura', models.ForeignKey(db_column='idasignatura', on_delete=django.db.models.deletion.DO_NOTHING, related_name='trabajadas', to='libretas.asignatura')),
            ],
            options={
                'db_table': 'asignatura_trabajada',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('IdBoleta', models.IntegerField(primary_key=True, serialize=False)),
                ('IdGrado_trabajado', models.IntegerField(blank=True, null=True)),
                ('IdTutor', models.IntegerField(blank=True, null=True)),
                ('Anio', models.IntegerField()),
                ('Promedio_Final_General', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('Comentarios_Tutor', models.TextField(blank=True, null=True)),
                ('Fecha_Emision', models.DateField(blank=True, null=True)),
                ('IdAlumno', models.ForeignKey(db_column='IdAlumno', on_delete=django.db.models.deletion.DO_NOTHING, related_name='boletas', to='libretas.alumno')),
            ],
            options={
                'db_table': 'boleta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('idnota', models.IntegerField(db_column='idnota', primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(blank=True, db_column='calificacion', decimal_places=2, max_digits=5, null=True)),
                ('nombre', models.CharField(blank=True, db_column='nombre', max_length=50, null=True)),
                ('bimestre', models.IntegerField(db_column='bimestre')),
                ('idalumno', models.ForeignKey(db_column='idalumno', on_delete=django.db.models.deletion.DO_NOTHING, related_name='notas', to='libretas.alumno')),
                ('idasignatura_trabajada', models.ForeignKey(db_column='idasignatura_trabajada', on_delete=django.db.models.deletion.DO_NOTHING, related_name='notas', to='libretas.asignaturatrabajada')),
            ],
            options={
                'db_table': 'nota',
                'managed': True,
            },
        ),
    ]
