# Generated by Django 5.2.7 on 2025-11-14 17:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cerrado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Bimestre',
                'verbose_name_plural': 'Bimestres',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='ConsolidadoUGEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre_1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('bimestre_2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('bimestre_3', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('bimestre_4', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('promedio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('letra', models.CharField(blank=True, choices=[('AD', 'Logro Destacado (18-20)'), ('A', 'Logro Esperado (14-17)'), ('B', 'En Proceso (11-13)'), ('C', 'En Inicio (00-10)')], max_length=2)),
                ('posicion_curso', models.IntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consolidacion.curso')),
            ],
            options={
                'verbose_name': 'Consolidado UGEL',
                'verbose_name_plural': 'Consolidados UGEL',
                'ordering': ['-promedio_final'],
                'unique_together': {('estudiante', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='ConsolidadoBimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_mensual_1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('promedio_mensual_2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('examen_bimestral', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('promedio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('posicion', models.IntegerField(blank=True, null=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('bimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consolidacion.bimestre')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consolidacion.curso')),
            ],
            options={
                'verbose_name': 'Consolidado Bimestral',
                'verbose_name_plural': 'Consolidados Bimestrales',
                'ordering': ['-promedio_final'],
                'unique_together': {('estudiante', 'curso', 'bimestre')},
            },
        ),
    ]
