# Generated by Django 5.2.7 on 2025-11-14 17:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('peso_porcentual', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Peso en el promedio (e.g., 0.20 para 20%)', max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Rubros',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('grado', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Secciones',
            },
        ),
        migrations.CreateModel(
            name='NotaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(help_text='1 a 12')),
                ('calificacion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calificación de 0.00 a 20.00', max_digits=4)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_mensuales', to=settings.AUTH_USER_MODEL)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.rubro')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.seccion')),
            ],
            options={
                'verbose_name': 'Nota Mensual',
                'verbose_name_plural': 'Notas Mensuales',
                'unique_together': {('estudiante', 'curso', 'seccion', 'rubro', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='ExamenBimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.IntegerField(help_text='1 a 4')),
                ('calificacion_examen', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calificación del examen bimestral de 0.00 a 20.00', max_digits=4)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_bimestrales', to=settings.AUTH_USER_MODEL)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.seccion')),
            ],
            options={
                'verbose_name': 'Examen Bimestral',
                'verbose_name_plural': 'Exámenes Bimestrales',
                'unique_together': {('estudiante', 'curso', 'seccion', 'bimestre')},
            },
        ),
        migrations.CreateModel(
            name='EstadoCierreMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto para Edición'), ('REVISION', 'En Proceso de Revisión'), ('CERRADO', 'Cerrado y Bloqueado')], default='ABIERTO', help_text='Estado de las notas: ABIERTO, REVISION o CERRADO.', max_length=10)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.curso')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.seccion')),
            ],
            options={
                'verbose_name': 'Estado Cierre Mensual',
                'verbose_name_plural': 'Estados Cierre Mensual',
                'unique_together': {('curso', 'seccion', 'mes')},
            },
        ),
    ]
