# Generated by Django 5.2.7 on 2025-11-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0001_initial'),
    ]

    operations = [
    ]
